name: Python application

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '0 */12 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.9
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install pysisyphus and dependencies required for testing
      run: |
        python -m pip install -e .[test]
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: >
        pytest -v
        --show-capture=no
        --durations=0
        tests
